# INTENSIVOS DE NUMPY Y ALGEBRA: EJERCICIOS

Estos ejercicios te permitirán repasar y consolidar lo que has aprendido en los intensivos de Numpy y Álgebra.

No hagas los ejercicios hasta que hayas estudiado y memorizado el contenido de sus notebooks.

Instrucciones:

* Crea una copia de este notebook antes de escribir nada. De esa forma respetarás el original para volver a hacerlo
* Cada ejercicio tiene unas instrucciones de lo que debes hacer en él
* Bajo las instrucciones estará una celda vacía, aquí es donde tú debes escribir la solución
* Y bajo esta última celda verás que hay otras dos celdas. La primera está vacía y no la debes tocar. Es para que tengas siempre a mano la solución al ejercicio, ya que esta no va a cambiar

## Ejercicio:

Importa numpy como np

In [1]:
import numpy as np

## Ejercicio:

Crea una lista de Python con los números del 1 a l0. Y después suma 5 a cada uno de sus elementos.

In [85]:
lista = list(range(1, 11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
# Version del profesor Isaac
[cada+5 for cada in lista]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [31]:
for i in range(len(lista)):
    lista[i] += 5

lista

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [46]:
#No tocar, es para que veas la solución

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## Ejercicio:

Haz lo mismo pero ahora usando numpy (primero crea un vector a partir de lista).

In [89]:
numpy_list = np.array(lista)
numpy_list+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
#No tocar, es para que veas la solución

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Ejercicio:

Crea un array directamente desde un rango, desde el 100 al 200 de 10 en 10.

In [37]:
rango_numpy = np.arange(100, 210, 10)
rango_numpy

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

In [49]:
#No tocar, es para que veas la solución

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

## Ejercicio:

Crea una array de 20 elementos interpolados desde el 100 al 200.

In [39]:
rango_20elem = np.linspace(100, 200, 20)
rango_20elem

array([100.        , 105.26315789, 110.52631579, 115.78947368,
       121.05263158, 126.31578947, 131.57894737, 136.84210526,
       142.10526316, 147.36842105, 152.63157895, 157.89473684,
       163.15789474, 168.42105263, 173.68421053, 178.94736842,
       184.21052632, 189.47368421, 194.73684211, 200.        ])

In [50]:
#No tocar, es para que veas la solución

array([100.        , 105.26315789, 110.52631579, 115.78947368,
       121.05263158, 126.31578947, 131.57894737, 136.84210526,
       142.10526316, 147.36842105, 152.63157895, 157.89473684,
       163.15789474, 168.42105263, 173.68421053, 178.94736842,
       184.21052632, 189.47368421, 194.73684211, 200.        ])

## Ejercicio:

Crea una matriz de 4 filas y 6 columnas rellena con ceros.

In [91]:
matriz_prof = np.zeros((4, 6))
matriz_prof

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
matriz_ceros = np.zeros((6, 4)).reshape(4, 6)
matriz_ceros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
#No tocar, es para que veas la solución

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Ejercicio:

Crea una matriz identidad de 4 filas y 4 columnas.

In [47]:
matrix_identidad = np.eye(4)
matrix_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
#No tocar, es para que veas la solución

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Ejercicio:

Crea una matriz de 6 filas y 3 columnas rellena con números aleatorios entre 0 y 1.

In [93]:
matri_prof_alea = np.random.randn(6, 3)
matri_prof_alea

array([[-0.19423703, -1.05193069, -0.20157242],
       [ 0.35980923, -0.47051451,  0.00537266],
       [-0.64931552, -1.80306684, -1.16175167],
       [ 3.10418161,  1.52564229, -0.44606054],
       [ 0.36970124, -0.51284831,  2.37761986],
       [ 0.29998058, -0.37883708, -0.76973543]])

In [65]:
matr_alea = np.random.randn(3, 6).reshape(6, 3)
matr_alea

array([[-0.13006885,  0.32602822, -0.5950688 ],
       [-0.31117117,  0.64148961,  0.16835671],
       [ 0.35615493,  2.49350773, -0.84890316],
       [ 0.38282237,  0.22972481,  0.01964894],
       [ 0.94272557,  0.09370964,  0.61788841],
       [ 1.95531114,  0.28342184,  0.79183109]])

In [53]:
#No tocar, es para que veas la solución

array([[0.09451382, 0.16584694, 0.2529427 ],
       [0.28996585, 0.46437665, 0.43470393],
       [0.46521979, 0.27674738, 0.07856732],
       [0.13936708, 0.82925581, 0.39132827],
       [0.43577272, 0.32297518, 0.06138335],
       [0.27166362, 0.54577411, 0.28245301]])

## Ejercicio:

Crea un vector aleatorio de 100 elementos que tenga una distribución normal.

In [67]:
vector_normal = np.random.randn(100)
vector_normal

array([ 0.26302018,  0.35958793, -1.0218233 , -0.3905256 , -2.2924422 ,
        0.06729452, -0.29546326,  0.6952156 , -0.5682995 ,  0.23386354,
        0.5452956 , -0.85558848, -0.99203372,  1.42728377,  0.41556442,
        0.81432402,  0.00561012,  0.27772816, -0.24503328,  0.43372947,
        0.20507424, -0.43904309, -0.40077347, -1.33104159, -0.80789418,
       -0.65485208,  0.32656277,  0.07927722, -0.0868792 ,  0.05066765,
       -0.35051969, -0.30341509, -1.39704112, -0.21863969, -1.20698883,
        0.39324742, -0.24864318, -0.36879961, -0.10729967, -1.22429762,
       -0.96217928, -1.13184485, -0.32463069,  0.79469381,  0.14312685,
        0.6011528 ,  1.81713985,  0.10326576,  0.58089086, -0.61112785,
       -0.59504643,  0.90149505, -1.36359498, -0.29195707, -1.63288629,
        1.63978528,  1.05130347,  1.30188268,  0.27991323, -0.40804407,
        0.59919134, -0.68613687,  0.61425872,  0.95991234, -0.00938198,
       -0.77084948, -0.54566561,  0.19401654, -0.86869902, -0.55

In [54]:
#No tocar, es para que veas la solución

array([ 0.12834816,  0.42524468,  0.21095275,  0.7218104 ,  0.09394681,
        0.4642257 , -0.11891562,  0.61751569,  0.75489449, -2.30931096,
       -1.75704714,  0.89818773,  0.15026191, -1.06121246, -0.39216193,
       -1.26625334, -0.64986291, -1.48819816,  0.02671956,  0.09407852,
       -0.38231459,  0.20115651, -0.03886299,  0.6251126 ,  0.80682781,
       -1.19814968, -0.50837248,  0.68435471,  0.71324418,  1.74594028,
        0.78351515, -1.50249539, -0.55837808,  0.61603342, -0.79127258,
        0.30382751, -0.45963241, -0.76974453, -0.45983724, -0.93955482,
        0.84061529,  0.95448884, -0.83919377,  0.52608214,  3.31969621,
       -0.768641  , -0.13039133,  0.31945984,  0.98480205, -0.41329785,
       -0.86605547,  1.86406004, -1.1478997 ,  2.46526731, -1.49621034,
        0.01154948,  1.64698209,  1.29050885,  1.12787419,  2.14417859,
       -1.91519325,  0.60085336, -0.66306722, -0.26413746,  0.03949464,
        0.7090535 , -0.21414052,  0.55457442, -0.35212701, -0.04

## Ejercicio:

Crea un vector aleatorio de 100 elementos que vayan entre el 1 y el 100.

In [70]:
vector_alea = np.random.randint(1, 101, 100)
vector_alea

array([68, 70, 49, 34, 55,  7, 31, 80, 12,  1, 20, 80, 46, 48, 61, 93,  1,
       75, 89, 18,  8, 58, 97, 86, 60, 27,  5, 33, 69, 50,  5, 19, 73, 49,
       95, 59, 44, 80, 45, 21, 59, 28,  4, 85, 28,  6, 92, 90,  2, 42, 59,
       17,  2, 36, 87,  4,  9, 72, 56, 21, 82, 63, 79, 60, 43,  6, 49,  1,
       75, 57, 27,  3, 45, 29, 40, 41, 79, 19, 96,  4, 77, 61, 90,  1,  1,
       43, 70, 94, 12, 45, 13, 45, 58, 82, 53, 14, 33, 72, 15, 91])

In [55]:
#No tocar, es para que veas la solución

array([ 13,  90,  91,  42,   3,  61,  81,  65,  66,  81,  36,  81,  28,
        50,  46,  69,  35,  95,  96,  21,  48,  96,   7,  40,  18,  12,
        25,  12,  38,  72,  91,  34,  66,  51,  95,   7,   1,  92,   6,
        28,  92,  15,  48,  18,  58,  24,  15,  21,  93,  28,  70,  71,
         8,  22,  54,  35,  46,  49,  78,  28,  94,  46,  73,  28,  94,
        21,  17,  54,  77,  39,  66,  51,  40,  35, 100,  90,  60,  46,
        23,  59,  56,  26,  30,  72,  86,  99,  33,  92,  50, 100,  91,
        35,  58,  96,  37,   8,  35,  54,  24,  31])

## Ejercicio:

Crea un vector llamado vector, como el anterior pero ordénalo.

In [73]:
vector_alea.sort()
vector_alea

array([ 1,  1,  1,  1,  1,  2,  2,  3,  4,  4,  4,  5,  5,  6,  6,  7,  8,
        9, 12, 12, 13, 14, 15, 17, 18, 19, 19, 20, 21, 21, 27, 27, 28, 28,
       29, 31, 33, 33, 34, 36, 40, 41, 42, 43, 43, 44, 45, 45, 45, 45, 46,
       48, 49, 49, 49, 50, 53, 55, 56, 57, 58, 58, 59, 59, 59, 60, 60, 61,
       61, 63, 68, 69, 70, 70, 72, 72, 73, 75, 75, 77, 79, 79, 80, 80, 80,
       82, 82, 85, 86, 87, 89, 90, 90, 91, 92, 93, 94, 95, 96, 97])

In [56]:
#No tocar, es para que veas la solución

array([ 1,  1,  1,  2,  2,  3,  3,  5,  5,  7,  8,  9, 11, 12, 17, 17, 19,
       19, 20, 20, 23, 24, 26, 26, 26, 27, 27, 28, 29, 32, 32, 33, 34, 35,
       35, 36, 40, 40, 40, 40, 45, 46, 50, 52, 53, 53, 55, 55, 55, 56, 56,
       57, 57, 57, 58, 59, 60, 61, 62, 63, 65, 66, 66, 66, 67, 68, 70, 71,
       71, 72, 73, 74, 74, 78, 78, 79, 79, 81, 81, 82, 82, 85, 85, 85, 85,
       86, 86, 87, 87, 88, 89, 91, 92, 93, 94, 95, 95, 95, 96, 98])

## Ejercicio:

Sobre vector calcula la media, mediana, desv típica, varianza, máximo y mínimo.

In [94]:
print(vector_alea.mean())
print(np.median(vector_alea))
print(np.std(vector_alea))
print(vector_alea.var())
print(vector_alea.max())
print(vector_alea.min())

45.88
45.5
29.854071749093123
891.2656000000002
97
1


In [57]:
#No tocar, es para que veas la solución

51.8
56.0
29.27422074112307
856.9800000000001
98
1


## Ejercicio:

Extrae de vector los elementos que están entre el sexto y el octavo ambos incluidos.

In [96]:
vector_alea[5: 8]

array([2, 2, 3])

In [58]:
#No tocar, es para que veas la solución

array([3, 3, 5])

## Ejercicio:

Extrae de vector los elementos que son pares. Pista: puedes apoyarte en el operador módulo %

In [99]:
vector_alea[vector_alea % 2 == 0]

array([ 2,  2,  4,  4,  4,  6,  6,  8, 12, 12, 14, 18, 20, 28, 28, 34, 36,
       40, 42, 44, 46, 48, 50, 56, 58, 58, 60, 60, 68, 70, 70, 72, 72, 80,
       80, 80, 82, 82, 86, 90, 90, 92, 94, 96])

In [59]:
#No tocar, es para que veas la solución

array([ 2,  2,  8, 12, 20, 20, 24, 26, 26, 26, 28, 32, 32, 34, 36, 40, 40,
       40, 40, 46, 50, 52, 56, 56, 58, 60, 62, 66, 66, 66, 68, 70, 72, 74,
       74, 78, 78, 82, 82, 86, 86, 88, 92, 94, 96, 98])

## Ejercicio:

Crea dos vectores de enteros llamados v1 y v2, cada uno de 5 elementos aleatorios entre 1 y 10 y súmalos.

In [78]:
v1 = np.random.randint(1, 11, 5)
v2 = np.random.randint(1, 11, 5)
print(v1)
print(v2)

[1 2 8 5 8]
[6 5 8 3 5]


In [79]:
v1+v2

array([ 7,  7, 16,  8, 13])

In [60]:
#No tocar, es para que veas la solución

array([10, 17, 10, 16, 15])

## Ejercicio:

Multiplícalos usando el producto escalar.

In [102]:
# np.dot(v1,v2) tambien es posible
v1.dot(v2)

135

In [61]:
#No tocar, es para que veas la solución

215

## Ejercicio:

Transforma el vector que creaste antes llamado vector en una matriz de 10 x 10 y llámala matriz

In [104]:
matris_vec = vector_alea.reshape(10, 10)
matris_vec

array([[ 1,  1,  1,  1,  1,  2,  2,  3,  4,  4],
       [ 4,  5,  5,  6,  6,  7,  8,  9, 12, 12],
       [13, 14, 15, 17, 18, 19, 19, 20, 21, 21],
       [27, 27, 28, 28, 29, 31, 33, 33, 34, 36],
       [40, 41, 42, 43, 43, 44, 45, 45, 45, 45],
       [46, 48, 49, 49, 49, 50, 53, 55, 56, 57],
       [58, 58, 59, 59, 59, 60, 60, 61, 61, 63],
       [68, 69, 70, 70, 72, 72, 73, 75, 75, 77],
       [79, 79, 80, 80, 80, 82, 82, 85, 86, 87],
       [89, 90, 90, 91, 92, 93, 94, 95, 96, 97]])

In [62]:
#No tocar, es para que veas la solución

array([[ 1,  1,  1,  2,  2,  3,  3,  5,  5,  7],
       [ 8,  9, 11, 12, 17, 17, 19, 19, 20, 20],
       [23, 24, 26, 26, 26, 27, 27, 28, 29, 32],
       [32, 33, 34, 35, 35, 36, 40, 40, 40, 40],
       [45, 46, 50, 52, 53, 53, 55, 55, 55, 56],
       [56, 57, 57, 57, 58, 59, 60, 61, 62, 63],
       [65, 66, 66, 66, 67, 68, 70, 71, 71, 72],
       [73, 74, 74, 78, 78, 79, 79, 81, 81, 82],
       [82, 85, 85, 85, 85, 86, 86, 87, 87, 88],
       [89, 91, 92, 93, 94, 95, 95, 95, 96, 98]])

## Ejercicio:

Multiplica matriz por 8

In [105]:
matris_vec*8

array([[  8,   8,   8,   8,   8,  16,  16,  24,  32,  32],
       [ 32,  40,  40,  48,  48,  56,  64,  72,  96,  96],
       [104, 112, 120, 136, 144, 152, 152, 160, 168, 168],
       [216, 216, 224, 224, 232, 248, 264, 264, 272, 288],
       [320, 328, 336, 344, 344, 352, 360, 360, 360, 360],
       [368, 384, 392, 392, 392, 400, 424, 440, 448, 456],
       [464, 464, 472, 472, 472, 480, 480, 488, 488, 504],
       [544, 552, 560, 560, 576, 576, 584, 600, 600, 616],
       [632, 632, 640, 640, 640, 656, 656, 680, 688, 696],
       [712, 720, 720, 728, 736, 744, 752, 760, 768, 776]])

In [63]:
#No tocar, es para que veas la solución

array([[  8,   8,   8,  16,  16,  24,  24,  40,  40,  56],
       [ 64,  72,  88,  96, 136, 136, 152, 152, 160, 160],
       [184, 192, 208, 208, 208, 216, 216, 224, 232, 256],
       [256, 264, 272, 280, 280, 288, 320, 320, 320, 320],
       [360, 368, 400, 416, 424, 424, 440, 440, 440, 448],
       [448, 456, 456, 456, 464, 472, 480, 488, 496, 504],
       [520, 528, 528, 528, 536, 544, 560, 568, 568, 576],
       [584, 592, 592, 624, 624, 632, 632, 648, 648, 656],
       [656, 680, 680, 680, 680, 688, 688, 696, 696, 704],
       [712, 728, 736, 744, 752, 760, 760, 760, 768, 784]])